name: Build and deploy ASP.Net Core app to Azure Web App - marketeersmarketplace

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./MarketeersMarketplace.sln --configuration Release

      - name: Publish the app
        run: dotnet publish ./MarketeersMarketplace.sln -c Release -o ${{ github.workspace }}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E61296122C0490091AE72C8368A34F3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FD48F47C63DB4E319B5EE5BFA8281762 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_067CF569A8BE41E3B0548841815E560A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'marketeersmarketplace'
          slot-name: 'Production'
          package: ${{ github.workspace }}/publish
